title: Your Name's Homepage
page-top-title: Your Name +++
top-section-bg-text: The 2026 International Workshop on Health Digital Twin (HDT 2026)
home-subtitle: Your Name ???
copyright-text: '&copy; Health Digital Twin 2026. All Rights Reserved.'
github-link: https://yuvisu.github.io/health-digitaltwin/

