title: Your Name's Homepage
page-top-title: HDT 2026
top-section-bg-text: The 2026 International Workshop on Health Digital Twin (HDT 2026)
home-subtitle: in Conjunction with the 14th IEEE International Conference on Healthcare Informatics ICHI 2026
            June 1, 2026, Minneapolis, MN, USA
copyright-text: '&copy; Health Digital Twin 2026. All Rights Reserved.'
github-link: https://yuvisu.github.io/health-digitaltwin/

