title: Your Name's Homepage
page-top-title: Your Name
top-section-bg-text: Your Research Area
home-subtitle: Your Name
copyright-text: '&copy; Your Name 2025. All Rights Reserved.'
github-link: https://github.com/yourusername

